services:
  django-app:
    build:
      context: ./django-app
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    env_file:
      - ./django-app/.env
    volumes:
      - ./django-app:/app
    environment:
      - CSRF_TRUSTED_ORIGINS=http://localhost:8000
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      PGDATA: /var/lib/postgresql/data/
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser -d django_docker_starter_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    shm_size: "2gb"

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      PGADMIN_LISTEN_PORT: 80
      GUNICORN_TIMEOUT: 300
    ports:
      - "4000:80"
    volumes:
      - pgadmin_data:/pgadmin4/servers.json
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-O-", "http://localhost:80/misc/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  pgadmin_data:
